#
# Build image
#
FROM continuumio/miniconda3 AS builder

WORKDIR /app
COPY . .

RUN apt update -y && apt upgrade -y && apt install curl -y
RUN apt install ffmpeg libsm6 libxext6 libgl1-mesa-glx -y
RUN apt install -y g++ ninja-build

# Create a conda environment with Python 3.10
RUN conda create -n env python=3.10
SHELL ["conda", "run", "-n", "env", "/bin/bash", "-c"]

RUN python -m pip install --upgrade pip setuptools wheel

RUN conda update -n base -c defaults conda

# Install dependencies
RUN conda env update -n env --file environment_input.yml

# Export the environment to a yml file
RUN conda env export > environment.yml

#
# Prod image
#

FROM continuumio/miniconda3 AS runtime

WORKDIR /app
COPY --from=builder /app/environment.yml .

# Create a conda environment with Python 3.10
RUN conda create -n env python=3.10
SHELL ["conda", "run", "-n", "env", "/bin/bash", "-c"]

# Install dependencies
RUN conda env update -n env --file environment.yml

RUN apt update -y && apt upgrade -y && apt install curl -y
RUN apt install ffmpeg libsm6 libxext6 libgl1-mesa-glx -y
RUN apt install -y g++ ninja-build

RUN python -m pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cu113

# Clone detectron2 and install it
RUN mkdir detectron2_v5
WORKDIR /app/detectron2_v5
RUN git clone https://github.com/facebookresearch/detectron2.git
RUN python -m pip install -e detectron2

WORKDIR /app
RUN mkdir api worker logic
#1 Ensure conda environment is activated by default
ENV PATH /opt/conda/envs/env/bin:$PATH
