#
# Build image
#
FROM continuumio/miniconda3 AS builder

WORKDIR /app
COPY . .

RUN apt update -y && apt upgrade -y && apt install curl -y

# Create a conda environment with Python 3.10
RUN conda create -n env python=3.10
SHELL ["conda", "run", "-n", "env", "/bin/bash", "-c"]

# Install dependencies
RUN conda env update -n env --file myenvPoetry1.yml

# Export the environment to a yml file
RUN conda env export > environment.yml

#
# Prod image
#

FROM continuumio/miniconda3 AS runtime

WORKDIR /app
COPY --from=builder /app/environment.yml .

# Create a conda environment with Python 3.10
RUN conda create -n env python=3.10
SHELL ["conda", "run", "-n", "env", "/bin/bash", "-c"]

# Install dependencies
RUN conda env update -n env --file environment.yml

# Ensure conda environment is activated by default
ENV PATH /opt/conda/envs/env/bin:$PATH
