name: "AppleMaskRCNNModel"
platform: "tensorflow_savedmodel"
max_batch_size: 0
input [
  {
    name: "conv2d_input"
    data_type: TYPE_FP32
    format: FORMAT_NHWC
    dims: [32,32,3]
  }
]
output [
  {
    name: "dense_1"
    data_type: TYPE_FP32
    dims: [10]
  }
]
