name: "ClassificationLinden"
platform: "tensorflow_savedmodel"
max_batch_size: 0
input [
  {
    name: "input_1"
    data_type: TYPE_FP32
    format: FORMAT_NONE
    dims: [365,302,3]
  }
]
output [
  {
    name: "dense_1"
    data_type: TYPE_FP32
    dims: [2]
  }
]
