name: "ClassificationLinden"
platform: "tensorflow_savedmodel"
max_batch_size: 0
input [
  {
    name: "vgg16_input"
    data_type: TYPE_FP32
    format: FORMAT_NHWC
    dims: [384, 321, 3]
  }
]
output [
  {
    name: "dense_1"
    data_type: TYPE_FP32
    dims: [2]
  }
]
